baseURL = "https://playful-cannoli-2eca65.netlify.app/"
languageCode = "en-us"
title = "Eaton Test Demo"


[languages]
  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    weight = 1
