baseURL = "https://playful-cannoli-2eca65.netlify.app/"
title = "Eaton Test Demo"
defaultContentLanguage = "en"
languageCode = "en-us"
theme = "ananke"

[params]
read_more_copy = "Read more about this entry"

