baseURL = "https://playful-cannoli-2eca65.netlify.app/"
defaultContentLanguage = "en"
title = "Eaton Test Demo"

# Use the Hugo Module syntax for the theme:
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]

[languages]
  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    weight = 1
